---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: ping de.de
      shell: ping de.de -c 4
    - set_stats:
        data:
           test: out_from test flow1
    - pause:
           prompt: reset accaunt
           seconds: 600
