---
- hosts: containers 
  vars_prompt:

   - name: service 
     prompt: service 
  tasks:
    - name: do something
      shell: ping de.de -c 4
    - name: restart service
      service: name={{ service }} state=restarted
