---
- hosts: localhost
  gather_facts: no
  tasks:
    # - name: include variable
    #   include_vars:
    #      file: reset.yml
    #      name: reset
    - name: check variable
      shell: cat reset| grep reset | awk '{print $2}'
      register: output
      retries: 100
      delay: 5
      until: output.stdout == 'true' or output.stdout == 'abort'
    - name: change value back
      replace:
        path: reset
        regexp: 'true|abort'
        replace: 'false'
