---
- hosts: 
  gather_facts: no
  tasks:
    - name: check ansible version
      shssssssssll: ansible --version
    - fail:
        msg: 'variable test not defined'
      when: test is not defined  
