---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check ansible version
      shell: ansible --version
    # - fail:
    #     msg: 'variable test not defined'
    #   when: test is not defined
    - set_fact:
          migrate: no
    - shell: echo done
      when: migrate=='yes'
